baseURL = "https://nadluzszamete.pl/"
defaultContentLanguage = "pl"
enableRobotsTXT = true
enableEmoji = true
summaryLength = 0

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
