[goldmark]
  [goldmark.renderer]
    unsafe = true

[highlight]
  noClasses = false
  anchorLineNos = false
  codeFences = true
  guessSyntax = true
  lineNos = false
  lineNumbersInTable = true

[tableOfContents]
  startLevel = 2
  endLevel = 4
  ordered = false
