colorScheme = "blowfish"
brandName = "Na Dłuższą Metę"
description = "Blog o sporcie, zdrowiu i inwestowaniu — o budowaniu kapitału w mięśniach i na koncie: wyzwania sportowe, zdrowe nawyki i podstawy inwestowania."
authorImage = "images/me.jpg"
ogFallbackImage = "images/maraton.jpg"
contactEmail = "maciejmazur@nadluzszamete.pl"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["sport", "zdrowie", "inwestowanie"]

[[socials]]
  name = "Strava"
  url = "https://www.strava.com/athletes/101065522"
[[socials]]
  name = "Instagram"
  url = "https://www.instagram.com/bestia_z_sierakowa/"
[[socials]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/maciej-mazur-90064b2b4"
[[socials]]
  name = "RSS"
  url = "/index.xml"

[header]
  layout = "basic"

[seo]
  metaDescriptionOrder = ["description", "summary", "site"]
